version: '3'
services:
  app1:
    image: mostafaa8/nodeorg:latest
    container_name: app1
    restart: always
    ports:
      - '3001:3000'
    networks:
      - app-network
  app2:
    image: mostafaa8/nodeorg
    container_name: app2
    restart: always
    ports:
      - '3002:3000'
    networks:
      - app-network
  load_balancer:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - '80:80'
    volumes:
      - ./loadBalancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_1
      - app_2
    networks:
      - app-network
  monitoring_database:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - app-network
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
